token: "700982608:AAEptKtJPkags21mDfv4PQEmjO1hzp_CeTg"
BotUsername: "@UniCTProvaBot"
mensa_channel: '@dmiinsidersprova'
path_avvisi: 'C:\\Users\Pierpaolo\\Desktop\\Telegram-ERSU-Bot\\avvisi.txt'
news_channel: '@dmiinsidersprova'
admin_chat: '@dmiinsidersprova'
